USE [SONALIKA_BGK]
GO

INSERT INTO [dbo].[SUPPLIER]
           ([SUPPLIER_NAME]
           ,[SUPPLIER_CONTACT_NO]
           ,[SUPPLIER_ADDRESS]
           ,[SUPPLIER_TYPE]
           ,[SUPPLIER_STATUS])
     VALUES
           ('Bangalore Tractor Spares'
           ,9902465979
           ,'Home Address'
           ,7
           ,4)
GO

DELETE FROM [dbo].[SALES_INVOICES] WHERE SELL_TYPE = 6

ALTER TABLE [dbo].[SALES_INVOICES] DROP CONSTRAINT FK_SALES_INVOICES_TRACTOR_PURCHASES

ALTER TABLE [dbo].[SALES_INVOICES] DROP COLUMN TRACTOR_ID

ALTER TABLE [dbo].[SALES_INVOICES] DROP COLUMN DC_NO

ALTER TABLE [dbo].[SALES_INVOICES] DROP COLUMN DC_DATE

ALTER TABLE [dbo].[SALES_INVOICES] DROP COLUMN IS_DC

CREATE TABLE [dbo].[DELIVERY_CHALAN](
	[DC_ID] [int] IDENTITY(1,1) NOT NULL,
	[DC_NO] [varchar](50) NOT NULL,
	[TRACTOR_ID] [int] NOT NULL,
	[SALES_INVOICE_ID] [int] NULL,
	[DC_DATE] [datetime] NOT NULL,
	[HYPOTHETICATION] [varchar](50) NULL,
	[IS_DC] [bit] NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
 CONSTRAINT [PK_DELIVERY_CHALAN] PRIMARY KEY CLUSTERED 
(
	[DC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DELIVERY_CHALAN]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERY_CHALAN_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO

ALTER TABLE [dbo].[DELIVERY_CHALAN] CHECK CONSTRAINT [FK_DELIVERY_CHALAN_CUSTOMER]
GO

ALTER TABLE [dbo].[DELIVERY_CHALAN]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERY_CHALAN_SALES_INVOICES] FOREIGN KEY([SALES_INVOICE_ID])
REFERENCES [dbo].[SALES_INVOICES] ([SALES_INVOICE_ID])
GO

ALTER TABLE [dbo].[DELIVERY_CHALAN] CHECK CONSTRAINT [FK_DELIVERY_CHALAN_SALES_INVOICES]
GO

ALTER TABLE [dbo].[DELIVERY_CHALAN]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERY_CHALAN_TRACTOR_PURCHASES] FOREIGN KEY([TRACTOR_ID])
REFERENCES [dbo].[TRACTOR_PURCHASES] ([TRACTOR_ID])
GO

ALTER TABLE [dbo].[DELIVERY_CHALAN] CHECK CONSTRAINT [FK_DELIVERY_CHALAN_TRACTOR_PURCHASES]
GO
